/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafe.management.system;

import dao.BillDao;
import dao.CategoryDao;
import dao.ProductDao;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Category;
import model.Product;

/**
 *
 * @author AKLakshan
 */
public class PlaceOrder extends javax.swing.JFrame {
    public int billId = 1;
    public int grandTotal = 0;
    public int productPrice = 0;
    public int productTotal = 0;
    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String mobileNumberPattern = "^[0-9]*$";
    public String userEmail;

    /**
     * Creates new form PlaceOrder
     */
    public PlaceOrder() {
        initComponents();
    }

    public PlaceOrder(String email) {
        initComponents();
        proNameTb.setEditable(false);
        proPriceTb.setEditable(false);
        addBtn.setEnabled(false);
        genBtn.setEnabled(false);
        JFormattedTextField tf = ((JSpinner.DefaultEditor) jSpinner1.getEditor()).getTextField();
        tf.setEnabled(false);
        userEmail = email;
    }
    
    public void productNameByCategory(String category){
        DefaultTableModel dtm = (DefaultTableModel) proSearchTable.getModel();
        dtm.setRowCount(0);
        ArrayList<Product> list = ProductDao.getAllRecordsByCategory(category);
        Iterator<Product> itr = list.iterator();
        while(itr.hasNext()){
            Product productObj = itr.next();
            dtm.addRow(new Object[]{productObj.getName()});            
        }     
        
    }
    
        public void filterProductByName(String name,String category){
        DefaultTableModel dtm = (DefaultTableModel) proSearchTable.getModel();
        dtm.setRowCount(0);
        ArrayList<Product> list = ProductDao.filterProductByName(name,category);
        Iterator<Product> itr = list.iterator();
        while(itr.hasNext()){
            Product productObj = itr.next();
            dtm.addRow(new Object[]{productObj.getName()});
            
        }     
        
    }
        
        public void clearProductFields(){
            proNameTb.setText("");
            proPriceTb.setText("");
            jSpinner1.setValue(1);
            totTb.setText("");
            addBtn.setEnabled(false);
            
        }
        
        public void validateFields(){
            String customerName = nameTb.getText();
            String customerMobileNumber = mobileTb.getText();
            String customerEmail = emailTb.getText();
            if(!customerEmail.equals("") && customerMobileNumber.matches(mobileNumberPattern) && customerMobileNumber.length()==10 && customerEmail.matches(emailPattern)&& grandTotal > 0){
                genBtn.setEnabled(true);
        }
            else{
                genBtn.setEnabled(false);
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mobileTb = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emailTb = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        catCb = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        searchTb = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        proSearchTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        proNameTb = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        proPriceTb = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        totTb = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        clrBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        lblGrand = new javax.swing.JLabel();
        genBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(190, 134));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        jLabel1.setText("PLACE ORDER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 26, -1, 49));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-screen-35.png"))); // NOI18N
        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 26, -1, 31));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("BILL ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 133, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("00");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 133, 34, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CUSTOMER DETAILS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("NAME");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 231, -1, -1));

        nameTb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameTb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTbKeyReleased(evt);
            }
        });
        jPanel1.add(nameTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 228, 210, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("MOBILE NUMBER");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 278, -1, -1));

        mobileTb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mobileTb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobileTbKeyReleased(evt);
            }
        });
        jPanel1.add(mobileTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 275, 210, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("EMAIL");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 327, -1, -1));

        emailTb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailTb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTbKeyReleased(evt);
            }
        });
        jPanel1.add(emailTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 324, 210, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("CATEGORY");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, -1, -1));

        catCb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        catCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catCbActionPerformed(evt);
            }
        });
        jPanel1.add(catCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 152, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("SEARCH");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        searchTb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchTb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTbKeyReleased(evt);
            }
        });
        jPanel1.add(searchTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 152, -1));

        proSearchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME"
            }
        ));
        proSearchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proSearchTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(proSearchTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 297, 332));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("NAME");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 51, -1));

        proNameTb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(proNameTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 170, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("PRICE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 130, 48, -1));

        proPriceTb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(proPriceTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 130, 178, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("QUANTITY");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, -1, -1));

        jSpinner1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 170, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("TOTAL");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 170, -1, -1));

        totTb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(totTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 170, 178, -1));

        addBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add to cart.png"))); // NOI18N
        addBtn.setText("ADD TO CART");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 210, -1, -1));

        clrBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clrBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        clrBtn.setText("CLEAR");
        clrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrBtnActionPerformed(evt);
            }
        });
        jPanel1.add(clrBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, -1, -1));

        ProTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "PRICE", "QUANTITY", "TOTAL"
            }
        ));
        ProTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ProTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 550, 285));

        jLabel14.setText("GRAND TOTAL: Rs.");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 560, 114, -1));

        lblGrand.setText("000");
        jPanel1.add(lblGrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, 40, -1));

        genBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generate bill & print.png"))); // NOI18N
        genBtn.setText("GENERATE BILL");
        genBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genBtnActionPerformed(evt);
            }
        });
        jPanel1.add(genBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 560, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/full-page-background.PNG"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        new Home(userEmail).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        billId = Integer.parseInt(BillDao.getId());
        jLabel3.setText(BillDao.getId());
        ArrayList<Category> list = CategoryDao.getAllRecords();
        Iterator<Category> itr = list.iterator();
        while(itr.hasNext()){
            Category categoryObj = itr.next();
            catCb.addItem(categoryObj.getName());
            
        }   
            String category = (String) catCb.getSelectedItem();
            productNameByCategory(category);
        
    }//GEN-LAST:event_formComponentShown

    private void searchTbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTbKeyReleased
        String name = searchTb.getText();
        String category = (String) catCb.getSelectedItem();
        filterProductByName (name, category);
    }//GEN-LAST:event_searchTbKeyReleased

    private void proSearchTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proSearchTableMouseClicked
        int index = proSearchTable.getSelectedRow();
        TableModel  model = proSearchTable.getModel();
        String productName = model.getValueAt(index, 0).toString();
        Product product = ProductDao.getProductByName(productName);
        proNameTb.setText(product.getName());
        proPriceTb.setText(product.getPrice());
        jSpinner1.setValue(1);
        totTb.setText(product.getPrice());
        productPrice = Integer.parseInt(product.getPrice());
        productTotal = Integer.parseInt(product.getPrice());
        addBtn.setEnabled(true);
        
    }//GEN-LAST:event_proSearchTableMouseClicked

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
       int quantity  = (Integer) jSpinner1.getValue();
       if(quantity <=1){
           jSpinner1.setValue(1);
           quantity = 1;
       }
       productTotal = productPrice * quantity;
       totTb.setText(String.valueOf(productTotal));
    }//GEN-LAST:event_jSpinner1StateChanged

    private void catCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catCbActionPerformed
        String category =(String) catCb.getSelectedItem();
        productNameByCategory(category);
    }//GEN-LAST:event_catCbActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String name = proNameTb.getText();
        String price = proPriceTb.getText();
        String quantity = String.valueOf(jSpinner1.getValue());
        DefaultTableModel dtm = (DefaultTableModel) ProTable.getModel();
        dtm.addRow(new Object[]{name,price,quantity,productTotal});
        grandTotal = grandTotal + productTotal;
        lblGrand.setText(String.valueOf(grandTotal));
        
        clearProductFields();
        validateFields();
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void clrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrBtnActionPerformed
        clearProductFields();
    }//GEN-LAST:event_clrBtnActionPerformed

    private void nameTbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTbKeyReleased
        validateFields();
    }//GEN-LAST:event_nameTbKeyReleased

    private void mobileTbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileTbKeyReleased
        validateFields();
    }//GEN-LAST:event_mobileTbKeyReleased

    private void emailTbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTbKeyReleased
        validateFields();
    }//GEN-LAST:event_emailTbKeyReleased

    private void genBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genBtnActionPerformed
        validateFields();
    }//GEN-LAST:event_genBtnActionPerformed

    private void ProTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProTableMouseClicked
        int index = ProTable.getSelectedRow();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to remove this product", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            TableModel model = ProTable.getModel();
            String total = model.getValueAt(index, 3).toString();
            grandTotal = grandTotal - Integer.parseInt(total);
            lblGrand.setText(String.valueOf(grandTotal));
            ((DefaultTableModel) ProTable.getModel()).removeRow(index);
            
        }
    }//GEN-LAST:event_ProTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProTable;
    private javax.swing.JButton addBtn;
    private javax.swing.JComboBox<String> catCb;
    private javax.swing.JButton clrBtn;
    private javax.swing.JTextField emailTb;
    private javax.swing.JButton genBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblGrand;
    private javax.swing.JTextField mobileTb;
    private javax.swing.JTextField nameTb;
    private javax.swing.JTextField proNameTb;
    private javax.swing.JTextField proPriceTb;
    private javax.swing.JTable proSearchTable;
    private javax.swing.JTextField searchTb;
    private javax.swing.JTextField totTb;
    // End of variables declaration//GEN-END:variables
}
