/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafe.management.system;

import javax.swing.JOptionPane;
import model.User;
import dao.UserDao;

/**
 *
 * @author AKLakshan
 */
public class Signup extends javax.swing.JFrame {

    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String mobileNumberPattern = "^[0-9]*$";

    public Signup() {
        initComponents();
        SaveBtn.setEnabled(false);

    }

    public void clear() {
        nameTb.setText("");
        emailTb.setText("");
        mobileTb.setText("");
        addTb.setText("");
        passTb.setText("");
        SaveBtn.setEnabled(false);

    }
    
    
    
    public void ValidateFields(){
        String name = nameTb.getText();
        String email = emailTb.getText();
        String mobileNumber = mobileTb.getText();
        String address = addTb.getText();
        String password = passTb.getText();
        if(!name.equals("")&& email.matches(emailPattern) && mobileNumber.matches(mobileNumberPattern) && mobileNumber.length()==10 && !address.equals("") && !password.equals(""))
            SaveBtn.setEnabled(true);
        else
            SaveBtn.setEnabled(false);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameTb = new javax.swing.JTextField();
        emailTb = new javax.swing.JTextField();
        mobileTb = new javax.swing.JTextField();
        passTb = new javax.swing.JPasswordField();
        addTb = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        ClrBtn = new javax.swing.JButton();
        ClBtn = new javax.swing.JButton();
        LogBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 134));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("SIGNUP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 157, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("NAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("EMAIL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("MOBILE NUMBER");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("ADDRESS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("PASSWORD");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        nameTb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameTb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTbKeyReleased(evt);
            }
        });
        jPanel1.add(nameTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 347, -1));

        emailTb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailTb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTbKeyReleased(evt);
            }
        });
        jPanel1.add(emailTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 347, -1));

        mobileTb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mobileTb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobileTbKeyReleased(evt);
            }
        });
        jPanel1.add(mobileTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 347, -1));

        passTb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passTb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passTbKeyReleased(evt);
            }
        });
        jPanel1.add(passTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 347, -1));

        addTb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addTb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addTbKeyReleased(evt);
            }
        });
        jPanel1.add(addTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 347, -1));

        SaveBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        SaveBtn.setText("SAVE");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, -1, -1));

        ClrBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ClrBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        ClrBtn.setText("CLEAR");
        ClrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClrBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ClrBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, -1, -1));

        ClBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ClBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        ClBtn.setText("CLOSE");
        ClBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ClBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, -1, -1));

        LogBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LogBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        LogBtn.setText("LOGIN");
        LogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LogBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("BREWSTER'S CAFE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 340, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/first page background.PNG"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -140, 1290, -1));

        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClBtnActionPerformed

        int a = JOptionPane.showConfirmDialog(null, "Do you really want to close the application", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_ClBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed

        User user = new User();
        user.setName(nameTb.getText());
        user.setEmail(emailTb.getText());
        user.setMobileNumber(mobileTb.getText());
        user.setAddress(addTb.getText());
        user.setPassword(passTb.getText());
        UserDao.save(user);
        clear();
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void ClrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClrBtnActionPerformed
        clear();
    }//GEN-LAST:event_ClrBtnActionPerformed

    private void nameTbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTbKeyReleased
        // TODO add your handling code here:
        ValidateFields();
    }//GEN-LAST:event_nameTbKeyReleased

    private void emailTbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTbKeyReleased
        // TODO add your handling code here:
        ValidateFields();
    }//GEN-LAST:event_emailTbKeyReleased

    private void mobileTbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileTbKeyReleased
        // TODO add your handling code here:
        ValidateFields();
    }//GEN-LAST:event_mobileTbKeyReleased

    private void addTbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addTbKeyReleased
        // TODO add your handling code here:
        ValidateFields();
    }//GEN-LAST:event_addTbKeyReleased

    private void passTbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTbKeyReleased
        // TODO add your handling code here:
        ValidateFields();
    }//GEN-LAST:event_passTbKeyReleased

    private void LogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogBtnActionPerformed
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_LogBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClBtn;
    private javax.swing.JButton ClrBtn;
    private javax.swing.JButton LogBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField addTb;
    private javax.swing.JTextField emailTb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mobileTb;
    private javax.swing.JTextField nameTb;
    private javax.swing.JPasswordField passTb;
    // End of variables declaration//GEN-END:variables
}
